name: Build and push to dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: marselscheer/datascience-ide

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date +%Y%m%d)" >> ${GITHUB_ENV}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull-request only build image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ env.IMAGE }}:${{ env.RELEASE_DATE }}
        if: github.event_name == 'pull_request'
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ env.RELEASE_DATE }}
        if: github.event_name != 'pull_request'
